### ISSUE TITLE
Automatic shard-db selector may not be efficient..

### ISSUE THREAD

**Issue by ndac-todoroki** [ndac-todoroki/ecto_shard_repo#2]
First I thought of a mechanism like this:

```elixir
User
|> where(id: 13)
|> ShardRepo.all() # This makes queries only to shard which contains id `13`
```
This could be done on `==`s and `in`s.

Although, when you have queries like `<` `>` etc., this is not the case. There are no ways to find out whether all repos should be used or not.

In fact, if we try to support all of the possible terms, it means we need to support all of [Ecto.Query.API](https://hexdocs.pm/ecto/Ecto.Query.API.html#content). That is not possible.

**Comment by ndac-todoroki** [comment]
Instead, we could only support Repo selecting in single INSERTs a.k.a. creations.

```elixir
%User{}
|> User.changeset(%{foo: "bar"})  # adds `:id` here somehow
|> ShardRepo.insert!(shard_key: :id)
```

Otherwise we could always use all the Repos.

**Comment by ndac-todoroki** [comment]
(Moreover, when we think about UUIDs and using `ilike` queries, we definitely could not narrow down Repo choices)

**Comment by ndac-todoroki** [comment]
This may be a different problem, but there may be cases where you want to lookup only on certain multiple databases.

```elixir
User
|> where([u], u.name ilike "foo")
|> Repo.all(shards_of: [db_1, db_3])  # no such option currently
```

Should this be an option for EctoShardRepo Queries?

**Comment by ndac-todoroki** [comment]
It is not productive to create automatic repo selectors for all `Ecto.Query.API`s...
Here, it is valid to use `+` in `where/3` within the Ecto layer, but it becomes an error within MySQL. No good way to handle these kinds of queries which may include invalid expressions in EctoShardRepo...
```
iex(1)> User |> where([u], u.id + 1) |> Repo.all  # normal Ecto.Repo

12:49:09.839 [debug] QUERY ERROR source="users" db=2.8ms queue=35.1ms
SELECT u0.`id`, u0.`name`, u0.`rank`, u0.`experience`, u0.`count_of_login` FROM `users` AS u0 WHERE (u0.`id` + CAST(1 AS boolean)) []
** (MyXQL.Error) (1064) (ER_PARSE_ERROR) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'boolean))' at line 1
    (ecto_sql) lib/ecto/adapters/sql.ex:618: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:551: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```
Furthermore, users can create custom macros with `fragment/1`. We just can't support all.

We can still try to narrow down selected Repos on certain queries only (such as `==`, `in`) and leave others search all Repos, but that makes `EctoShardRepo` ambiguous, because you cannot know what happens when you perform a nested query.

Maybe simplifying to support only `lookup all repos` and adding support for _explict selecting multiple repos_ should be better.
